name: textfield_plus
description: "A highly customizable and easy-to-use text field widget for Flutter."
version: 0.1.2
homepage: https://github.com/sanalsanjanz/textfield_plus
repository: https://github.com/sanalsanjanz/textfield_plus
issue_tracker: https://github.com/sanalsanjanz/textfield_plus/issues
documentation: https://github.com/sanalsanjanz/textfield_plus/wiki

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
